### PR TITLE
Add HC32F46x support (Aquila X2 HC32 boards)

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description

https://github.com/shadow578/Marlin-H32

### CODE REVIEW

**Comment by mriscoc** [comment]
@classicrocker883 is this PR ready to be merged? I don't have the printer/board to do the respective test.

**Comment by classicrocker883** [comment]
i would say yes you can merge, however there may be a couple extra changes before you do, ill post them.

**Comment by classicrocker883** [comment]
ok i posted everything. however if you do update to more recent Marlin version, there is an additional change needed in **/src/module/stepper.cpp**, under `hal_timer_t Stepper::calc_timer_interval`
```
  #ifdef CPU_32_BIT

    // A fast processor can just do integer division
    TERN(TARGET_HC32F46x, const, constexpr) uint32_t min_step_rate = uint32_t(STEPPER_TIMER_RATE) / HAL_TIMER_TYPE_MAX;
    return step_rate > min_step_rate ? uint32_t(STEPPER_TIMER_RATE) / step_rate : HAL_TIMER_TYPE_MAX;

  #else
```

**Comment by mriscoc** [comment]
> ok i posted everything. however if you do update to more recent Marlin version, there is an additional change needed in **/src/module/stepper.cpp**, under `hal_timer_t Stepper::calc_timer_interval`

Hmm ok, maybe it's better to wait. I have a new version coming soon, it is based on a recent Marlin bug fix and will have a lot of changes because it integrates support for the CV laser module.

**Pull request closed without merging**
