### PR TITLE
Update proui.py - exit to FAILED, fix to allow SD ext toggle

### PR DESCRIPTION
**Pull request by classicrocker883**
makes it so it exits with FAILED instead of Success  
change Conditionals_Post.h to fix SD extender toggle.

### Description
changed `exit()` to add an error and display the message to exit with **FAILED** instead of **SUCCESS**

when SD extender is enabled, it will also `#undef SD_DETECT_PIN` so that when SD card is taken out or put back in LCDMESSAGE does not appear, and with SD extender toggled off, SD card does not reload when mounted.

this fixes the issue.

### CODE REVIEW

**Comment by mriscoc** [comment]
If you don't have an SD extender cable do not enable HAS_SD_EXTENDER, that will allow you to toggle Media update. HAS_SD_EXTENDER only has meaning if DWIN_LCD_PROUI is enabled.

**Comment by classicrocker883** [comment]
> If you don't have an SD extender cable do not enable HAS_SD_EXTENDER, that will allow you to toggle Media update. HAS_SD_EXTENDER only has meaning if DWIN_LCD_PROUI is enabled.

for firmware builds there is the option to enable Media - SD card auto mount. meaning if you don't have an SD extender you can simply uncheck the box, but if you decide to install one it's as easy as checking the box rather than rebuilding compiling new firmware with the option enabled.

however if you wanted to turn off the SD extender option through the lcd screen, it doesn't have SD detect pin enabled because of Conditionals_post.h option.

this fix helps it so SD card extender can be enabled through all firmware builds, and toggled on or off rather than making a whole new binary for without the option.

**Comment by mriscoc** [comment]
HAS_SD_EXTENDER is only for permanent use of SD card extender, if you want to enable/disable the support you need to keep HAS_SD_EXTENDER disabled.

**Comment by classicrocker883** [comment]
> HAS_SD_EXTENDER is only for permanent use of SD card extender, if you want to enable/disable the support you need to keep HAS_SD_EXTENDER disabled.

oh I see now. I didn't notice it was `IF_DISABLED(HAS_SD_ENTENDER)`

I see now.

**Comment by mriscoc** [comment]
I saw your contribution on Github sponsors, thanks.

**Pull request closed without merging**
