### PR TITLE
M48 fix, pause screen. Tram Wiz / Mesh View fix

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
Changed `ProbeTest()` to allow probe to be at the center of bed for better repeatability. Made it 5 instead of 10.
Disable High Speed Mode while probing for accuracy, then renable it when M48 is done.

Added a pause screen so no other things can be accidently pressed while it does the test.  

Recent edit:
---
added `static` to zval because
>The "static" keyword in this context means that the variable "zval" will be allocated once and will retain its value across multiple function calls.

I also added a fix to the Tramming Wizard, it used to load saying not leveled. and if values were 0.00 it would say lower (corner).
Put `EXIT_TRAMWIZ:` as a fail safe if value is 0.00 instead of saying not leveled.

<br>
<br>

fixed meshviewer so values arent limited to 0.20 like in this picture

<br>

### Benefits
More than 5 times to probe the bed for M48 isnt necessary, similar results for 5 vs 10.

Pausing the LCD screen so nothing else can be touched while it does the test.

HS mode disabled for better accuracy, then automatically re-enable if it was previously enabled.

Probes the center for consistency.

---
for meshviewer even though for the mesh, values shouldnt be +/-0.20, it can now display the true value.

### CODE REVIEW

**Comment by classicrocker883** [comment]
just a heads up -- with the newest Marlin, since the MString update, I was able to add
```
static void set_status(FSTR_P const, int8_t); 
// set_status undefined reference libproui.a workaround
```
to **src/lcd/marlinui.h**

---

```
  void MarlinUI::set_status(FSTR_P const fstr, int8_t level) {
    _set_status_and_level(FTOP(fstr), level);
  }
 // PROUI_EX workaround libproui.a undefined reference
```
to **src/lcd/marlinui.cpp**

<br>
so if you plan to update your code this is the workaround I had to do to make it work, it should help you whenever you start updating to the recent Marlin version.

**Comment by mriscoc** [comment]
M48 no need to be at the center, it can be done in any place over the bed, in fact there are the `XY` parameters for set where to do the test. The number of probes is a matter of taste, I prefer to leave it in 10 and if someone wants to change it, can use the parameter `P`. High speed mode should be respected because it will reflect the accuracy of the current settings. The popup screen for avoiding user interaction when running M48 is a good idea.

**Comment by classicrocker883** [comment]
so does M48 with HS mode on or without matter? instead of keeping HS mode off for better accuracy?
I would say it may be better to keep the amount of times it probes to a minimum incase of outliers which will effect the end result. and after some tests there really is little difference if the probe is always consistent.

while it can technically probe any position XY, wouldn't it be best in the same position it *Home's* **Z**? or how does M48 compare its value, from the first probe *after* homing?

edit: 
I made some additional changes, specifically to Tramming WIzard and bed Meshviewer.

**Comment by mriscoc** [comment]
> I made some additional changes, specifically to Tramming WIzard and bed Meshviewer.

We have a Telegram group where experimental versions are released with bug fixes and new features. You should test those versions first so you don't work twice as hard. The source code of the experimental versions is not public until the firmware is released.

**Comment by mriscoc** [comment]
Not applicable to the current version.

**Pull request closed without merging**
