### PR TITLE
Fixes for March 2024

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
Updated for Newest in 2024
---

- update spacing
- arrange PID plot code spacing to be more user friendly
- fixed some dependencies
- fixed typos

this code gives error  
`  void applyHomeOffset() { set_home_offset(hmiValue.select, menuData.value / MINUNITMULT); }`  
added `(AxisEnum)hmiValue.select`

### Related Issues

`OPTIMIZED_MESH_STORAGE` appears to be required for UBL, there should be a warning.

### CODE REVIEW

**Comment by mriscoc** [comment]
NOTE: This PR could break the PROUI_EX's functionality in G-code preview and Mesh viewer Pro.

**Comment by classicrocker883** [comment]
> NOTE: This PR could break the PROUI_EX's functionality in G-code preview and Mesh viewer Pro.

I do not see an issue with either. what specifically would cause that?

**Review by classicrocker883 — COMMENTED** [review]
@mriscoc please check out for review. this **PR** is needed

**Comment by mriscoc** [comment]
Sorry but this PR has too much changes, I prefer to manage atomic changes, only a few lines and directly related to an issue.

**Comment by classicrocker883** [comment]
it really isnt that many when you look at it. plus it addresses needed changes which cant be done single one by one, it has to be done all at once.
each file only had one or two changes, except for maybe a couple files.

most of these changes are typo related

**Pull request closed without merging**
