### PR TITLE
Add options to reduce image quality to fix thumbnails on TJC displays

### PR DESCRIPTION
**Pull request by Luro02**
### Description

This PR changes the thumbnail generation script for CURA. It adds an option to set the maximum size of the generated thumbnail in bytes. It then lowers the quality of the generated thumbnail until the size is less than the maximum size.

For **TJC** displays the dimensions must be exactly 200x200px and the generated thumbnail should
not be larger than 20kbytes. Sometimes the script made thumbnails that were larger than the 20kb, which resulted in an error about "missing thumbnail" on my Ender 3 S1.

I hid the option behind a checkbox, so the quality is only lowered when the option is set:
image
image
image

(by default the maximum size is set to about 15kb, if the box is checked)

### Benefits

- Adds option to reduce thumbnail size (-> generated gcode will be smaller as well)
- Makes thumbnail generator work with TJC displays

### Related Issues

This might be related to #990.

### CODE REVIEW

**Comment by mriscoc** [comment]
I like the additional option, but since there is only one additional option at the moment, perhaps it could be displayed without the need to use the checkbox. Maybe a line separator between the normal options and the "extra" option.

**Comment by Luro02** [comment]
I hid it behind a checkbox, so one can opt to not reduce the quality of the produced image. I could not find a way to leave the box empty by default, except with using a string box (but that has its own problems, like allowing invalid input). Ideally I would like to have it set to <20kb by default, so for all TJC users (who most likely do not read the wiki that thoroughly) the thumbnails will just work.

Would you mind telling me how to add a line separator? The documentation and examples are quite limited for cura plugins. (Maybe I haven't found the right page yet)

**Comment by mriscoc** [comment]
Maybe the attached file can help, sorry I couldn't find a newer version. 

[Cura_Data_Model.pdf](https://github.com/mriscoc/Ender3V2S1/files/12166926/Cura_Data_Model.pdf)

**Comment by Luro02** [comment]
I removed the checkbox
image
and instead allow -1 as a value
image
in which case the image size will remain unchanged

**Comment by Luro02** [comment]
I added a bit more code to speed up the search for an optimal thumbnail size. Before it started at a quality of 95 and then reduced it, until the produced image had a size less than the maximum thumbnail size.

The algorithm is simple, but slow, especially in the worst-case scenario: When the image is set to a very low value like 100 bytes (which no image could possibly satisfy), it tries all qualities from 95 to 1, so the snapshot is encoded 95 times. The new one will only need to encode the image ~6 times in the worst-case scenario (log_2(n) runtime for binary search):

image

#### The algorithm works like this:
The image qualities are proportional to the image sizes and this can be used to find
the best size faster through binary search.

For example when the size should be 15kb, one starts with the middle of the list of possible image qualities (`48` for `range(1, 95 + 1)`). This might produce an image with a size of 17kb. Now one knows that the quality must be less than `48`, because all qualities larger than that will produce images that are too large.

Then the quality is halved again (`quality=24`), which might produce an image of size 3kb. Based on this one knows that the ideal quality must be between `24` and `48`. The process is repeated, until the optimal image size has been found.

**Comment by mriscoc** [comment]
Merged https://github.com/mriscoc/Ender3V2S1/commit/aeae59adbc404590d5dbe60d0ce636cfa8adc8e5

**Comment by Luro02** [comment]
Thank you 🎉

**Pull request closed without merging**
